# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PAPER Planes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PAPER Planes

# add the Firebase pod for Google Analytics
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Email'
pod 'FirebaseUI/Google'
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'MessageKit'


# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  target 'PAPER PlanesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PAPER PlanesUITests' do
    # Pods for testing
  end

end
