# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PAPER Planes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PAPER Planes

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  target 'PAPER PlanesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PAPER PlanesUITests' do
    # Pods for testing
  end

end
